name: csr-salad
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - biopython>=1.79
  - numpy>=1.20.0
  - pandas>=1.3.0
  - jupyterlab>=3.0.0
  - ipython>=7.0.0
  - matplotlib>=3.3.0
  - pip
  - pip:
    - ipywidgets
